FROM ubuntu:18.04

# conda path
ENV PATH /opt/conda/bin:$PATH
# use C.UTF-8 locale 
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# R pre-requisites ++
RUN apt-get update --fix-missing && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    wget \
    unzip \
    ca-certificates \
    locales \
    fonts-dejavu \
    build-essential \
    gfortran \
    libxml2-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    r-base \
    r-base-dev \
    r-recommended \
    default-jdk \
    groff-base \
    libblas-dev \
    libbz2-dev \
    libcairo2-dev \
    libjpeg-dev \
    liblapack-dev \
    liblzma-dev \
    libncurses5-dev \
    libpango1.0-dev \
    libpcre3-dev \
    libpng-dev \
    libreadline-dev \
    libtiff5-dev \
    libx11-dev \
    libxt-dev \
    mpack \
    subversion \
    tcl8.6-dev \
    texinfo \
    texlive-base \
    texlive-extra-utils \
    texlive-fonts-extra \
    texlive-fonts-recommended \
    texlive-generic-recommended \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-latex-recommended \
    tk8.6-dev \
    x11proto-core-dev \
    xauth \
    xdg-utils \
    xfonts-base \
    xvfb \
    zlib1g-dev \
    libopenblas-dev \
    git \
    python-argparse && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s /bin/tar /bin/gtar
RUN R --slave -e "options(unzip='/usr/bin/unzip')"
RUN R --slave -e "install.packages(c('argparse', 'Matrix', 'devtools', 'withr'), repos='https://cloud.r-project.org/', lib='/usr/lib/R/library')"
RUN R --slave -e "withr::with_libpaths(new='/usr/lib/R/library', devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0'))"
