FROM ubuntu:18.04

# conda path
ENV PATH /opt/conda/bin:$PATH
# use C.UTF-8 locale 
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

# R pre-requisites ++
RUN apt-get update --fix-missing && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    wget \
    unzip \
    ca-certificates \
    locales \
    fonts-dejavu \
    build-essential \
    gfortran \
    libxml2-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    r-base \
    r-base-dev \
    r-recommended \
    default-jdk \
    groff-base \
    libblas-dev \
    libbz2-dev \
    libcairo2-dev \
    libjpeg-dev \
    liblapack-dev \
    liblzma-dev \
    libncurses5-dev \
    libpango1.0-dev \
    libpcre3-dev \
    libpng-dev \
    libreadline-dev \
    libtiff5-dev \
    libx11-dev \
    libxt-dev \
    mpack \
    subversion \
    tcl8.6-dev \
    texinfo \
    texlive-base \
    texlive-extra-utils \
    texlive-fonts-extra \
    texlive-fonts-recommended \
    texlive-generic-recommended \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-latex-recommended \
    tk8.6-dev \
    x11proto-core-dev \
    xauth \
    xdg-utils \
    xfonts-base \
    xvfb \
    zlib1g-dev \
    libopenblas-dev \
    git \
    python-argparse && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s /bin/tar /bin/gtar
RUN R --slave -e "options(unzip='/usr/bin/unzip')"
RUN R --slave -e "install.packages(c('argparse', 'Matrix', 'devtools', 'withr'), repos='https://cloud.r-project.org/', lib='/usr/lib/R/library')"
RUN R --slave -e "withr::with_libpaths(new='/usr/lib/R/library', devtools::install_github(repo = 'satijalab/seurat', ref = 'release/3.0'))"

#RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.4.10-Linux-x86_64.sh -O ~/miniconda.sh && \
#    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
#    rm ~/miniconda.sh && \
#    /opt/conda/bin/conda clean -tipsy && \
#    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
#    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
#    echo "conda activate base" >> ~/.bashrc

#ENV TINI_VERSION v0.18.0
#ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
#RUN chmod +x /usr/bin/tini
#
#RUN conda update conda
#RUN conda config --add channels defaults && \
#    conda config --add channels bioconda && \
#    conda config --add channels conda-forge

#RUN conda install --quiet --yes scanpy 

#RUN pip --no-cache-dir install phate