configfile:
    'config.yaml'

include:
    '../single-cell.sm'

QUANT = ['cellranger', 'star']

rule sample_info:
    output:
        'data/processed/sample_info.txt'
    run:
       import pandas as pd
       df = pd.DataFrame.from_dict(config['samples'], orient='index')
       df['Sample_ID'] = df.index
       df.to_csv(output[0], sep='\t', index=False)
    
rule test_filter:
    input:
        expand(rules.fastp_10x.output, sample=SAMPLES)

rule test_quant:
    input:
        expand(join('data', 'tmp', 'singlecell', 'quant', '{quant}', '{sample}', 'scanpy/adata.h5ad'), sample=SAMPLES, quant=QUANT)
