configfile:
    'config.yaml'

include:
    '../single-cell.sm'
include:
    '../rules/quant/velocyto.rules'

QUANT = ['star', 'alevin', 'umitools']
import pprint
print(SAMPLES)
pprint.pprint(config)

rule sample_info:
    output:
        join(PROCESSED_DIR, 'sample_info.txt')
    run:
       import pandas as pd
       df = pd.DataFrame.from_dict(config['samples'], orient='index')
       df['Sample_ID'] = df.index
       df.to_csv(output[0], sep='\t', index=False)
    
rule test_filter:
    input:
        expand(rules.fastp_10x.output, sample=SAMPLES)

rule test_quant:
    input:
        expand(join(INTERIM_DIR, 'singlecell', 'quant', '{quant}', '{sample}', 'scanpy/adata.h5ad'), sample=SAMPLES, quant=QUANT)

rule test_quant_aggr:
    input:
        expand(join(INTERIM_DIR, 'singlecell', 'quant', 'aggregate', '{quant}', 'scanpy', 'scanpy_aggr.h5ad'), quant=QUANT)
